const praias = [
    {
        id: 1,
        nome: "Praia dos Ingleses",
        regiao: "norte",
        orla: 4830,
        recomenda: false,
        foi: true,        
    },
    {
        id: 2,
        nome: "Praia Brava",
        regiao: "norte",
        orla: 1500,
        recomenda: true,
        foi: true,        
    },
    {
        id: 3,
        nome: "Praia de Canasvieiras",
        regiao: "norte",
        orla: 2200,
        recomenda: false,
        foi: true,        
    },
    {
        id: 4,
        nome: "Praia da Joaquina",
        regiao: "leste",
        orla: 3000,
        recomenda: true,
        foi: true,        
    },
    {
        id: 5,
        nome: "Praia Mole",
        regiao: "leste",
        orla: 960,
        recomenda: true, 
        foi: true,
    },
    {
        id: 6,
        nome: "Praia do Moçambique",
        regiao: "leste",
        orla: 8500,
        recomenda: true,
        foi: true,
    },    
    {
        id: 7,
        nome: "Praia do Campeche",
        regiao: "sul",
        orla: 3000,
        recomenda: true,
        foi: true,        
    },
    {
        id:8,
        nome: "Praia do Matadeiro",
        regiao: "sul",
        orla: 850,
        recomenda: true,
        foi: true,        
    },
    {
        id:9,
        nome: "Praia de Naufragados",
        regiao: "sul",
        orla: 950,
        recomenda: true,
        foi: true,        
    },
]

module.exports = praias